### ISSUE TITLE
Files stop saving after a while and existing files opened after that appear empty Windows 10

### ISSUE THREAD

**Issue by emeraldtip** [SpartanJ/ecode#85] opened 2023-03-19 14:04 UTC
I don't know why this is happening, I don't know how to reproduce it, I just know that sooner or later it just stops working.
Using save as just fails to save anything

https://user-images.githubusercontent.com/48155462/226181093-1b0d78fd-05d3-422b-a554-c27e9678c844.mp4

Also new files opened that have data inside of em appear to be empty.

https://user-images.githubusercontent.com/48155462/226181102-b96f2b22-ee61-4d46-9bda-2ee0c208afc7.mp4

Things work fine for a while after the restart, but then it happens again

**Comment by SpartanJ** [comment] 2023-03-19 15:35
That's really weird! Do you remember how you ended up with a file without a name? The "*" title bar indicates that the filename is basically empty for the editor which is super odd, at some point you mouse hover the tab and the path actually has a file name (converter3.py). If you move this folder outside of "OneDrive" stills happen? I suspect a read/write permissions issue that breaks everything at some point.

**Comment by emeraldtip** [comment] 2023-03-19 15:40
So the file stops saving at first and then when you switch to another tab and switch back to the original tab the filename disappears.

I'll try to see if it'll happen outside of onedrive

**Comment by SpartanJ** [comment] 2023-03-19 15:46
In the second video when you try to save using "Save As..." alerts that cannot write the file seem to be indicative of some permissions issue. The editor is not verbose about it and it should be. But I have no idea why it can write the file, can you also try to open ecode as administrator? I'll try to simulate the issue locally by removing write permissions to the files edited inside ecode.

**Comment by SpartanJ** [comment] 2023-03-19 15:50
Ok, on Linux if I try to save and I don't have permissions it simply never saves the file and keeps being in a modified state. Which isn't too bad. I'm clueless then.

**Comment by SpartanJ** [comment] 2023-03-19 16:47
I was able to reproduce it. It happens with read-only files on Windows. I played a little bit with the OneDrive folder. It seems that OneDrive creates Read Only files, but the issue happens when you make a change over a read-only file, try to save that change, the file fails to save, and then you undo the changes, I have a 100% repro rate doing that.

**Comment by emeraldtip** [comment] 2023-03-19 18:18
Tested it and it still happens even if I'm not in a onedrive folder

**Comment by SpartanJ** [comment] 2023-03-19 18:21
Yes, it will happen with read only files, it doesn't matter its location. But it seems that the reason of those files being read only is OneDrive weird permission management.

**Comment by emeraldtip** [comment] 2023-03-19 18:37
But why would onedrive's permission management affect files outside the onedrive folder?

**Comment by SpartanJ** [comment] 2023-03-19 18:58
It won't. The issue is how the editor manages read only files. If you copy and paste files with read only permissions, the issue will continue. In your case what you have to do is recursively remove all read only permissions from your project folder. I'll fix the issue ASAP and it will be fixed for the next release. ecode's won't be able to change any files permissions, but it will notify the user and won't get crazy about it like is doing currently.

**Comment by emeraldtip** [comment] 2023-03-19 19:38
Aight

**Closed** 2023-03-19 22:51 UTC
Labels: bug, windows
