### ISSUE TITLE
How to get rid of the auto complete suggestion?

### ISSUE THREAD

**Issue by chatchoi** [SpartanJ/ecode#342] opened 2024-10-01 08:58 UTC
Typing either tab or enter will insert the suggestion which I don't want to. It's the end of the line so I don't want to type space. It's really annoying. I ended up disabled the plugin.

It's either tab or enter. There must be a way to cancel the suggestion. If enter is for insert then tab is for cancel, and vice versa. Why do you make both tab and enter to do the same thing? Can you make it more sane?

**Comment by SpartanJ** [comment] 2024-10-01 14:14
This is a duplicate of #337, please check my comment there, keybindings were implemented to make this customisable, it will be released in 0.6.2 or you can try using the nightly builds [here](https://github.com/SpartanJ/eepp/releases/tag/nightly).

> There must be a way to cancel the suggestion.

In doubt always try escape, most of the things can be canceled with escape.

If you have any other need please leave a suggestion in #337.

**Closed by SpartanJ** 2024-10-01 14:14 UTC
Labels: duplicate
