### ISSUE TITLE
[0.4.4] Freezing on Windows after switching projects multiple times

### ISSUE THREAD

**Issue by andy0x10** [SpartanJ/ecode#45] opened 2023-02-10 14:36 UTC
Today I have managed to get ecode to freeze (lock-up) several times.

This has never happened before.

The only thing I've been doing differently today is switching between folders (projects) several times.

![image](https://user-images.githubusercontent.com/124288474/218118015-81d293c2-0f41-4226-86fc-df199c00f134.png)

I'm not sure what other information I can provide to help find the bug.

Thanks,

**Comment by SpartanJ** [comment] 2023-02-10 14:38
That's probably because it's still scanning all folders while you open new folders. I think i forgot to stop the scanning when changing folders (the scan is really fast in SSDs and never thought about it).

**Comment by andy0x10** [comment] 2023-02-10 14:39
Yep, that might be it.

I'm running on a fast NVME SSD though... but still it sounds likely as there are a ton of files in some of these project subfolders.

Thanks,

**Comment by andy0x10** [comment] 2023-02-10 14:43
Sure, where do I find the logs?

**Comment by SpartanJ** [comment] 2023-02-10 14:44
Linux: uses XDG_CONFIG_HOME, usually translates to ~/.config/ecode/ecode.log
macOS: uses Application Support folder in HOME, usually translates to ~/Library/Application Support/ecode/ecode.log
Windows: uses APPDATA, usually translates to C:\Users\{username}\AppData\Roaming\ecode\ecode.log

**Comment by andy0x10** [comment] 2023-02-10 14:47
[ecode.log](https://github.com/SpartanJ/ecode/files/10708459/ecode.log)

**Comment by andy0x10** [comment] 2023-02-10 15:10
Just happened again while I was typing..

![image](https://user-images.githubusercontent.com/124288474/218126144-b05e84a3-fae5-43cf-a68b-00e3dadf546a.png)

Hmmm...

**Comment by SpartanJ** [comment] 2023-02-10 15:11
I think it's the LSP. LSP is broken in 0.4.4 on Windows, please use this build: 
[ecode-windows-0.4.4-x86_64.zip](https://github.com/SpartanJ/ecode/files/10708771/ecode-windows-0.4.4-x86_64.zip). It should fix the issue...

**Comment by SpartanJ** [comment] 2023-02-10 15:23
Let me know if you get diagnostics and code completion in the new build. Something weird is going on with Omnisharp. Also if you can run ecode with debug log will be really helpful, debug logs are enabled by running `ecode.exe -ldebug`.

**Comment by andy0x10** [comment] 2023-02-11 11:08
[ecode.log](https://github.com/SpartanJ/ecode/files/10713458/ecode.log)

Here's a new log...seems to be an exception - not sure if that's the cause of the freezing or something else.

I can remove Omnisharp to see if it still has this issue..  It's easy to reproduce for me with this project.

Thanks,

**Comment by andy0x10** [comment] 2023-02-11 12:17
Yes, without Omnisharp the freeze doesn't seem to happen.  Aslo I noticed a bunch of zombie Omnisharp.exe processes that must have been related to each time I force closed ecode.  

I hope this helps but not sure what you can do to fix it :-)

Let me know if you need any more information.

Cheers,

**Comment by SpartanJ** [comment] 2023-02-11 16:01
It seems I don't gracefully handle a stuck LSP, my theory is that all the pool threads are being frozen by the LSP. I'll check out how to reproduce it. Your particular case should be easy to fix, the OmniSharp installation is lacking MSBuild that it's required to properly function. You need to [install MSBuild](https://github.com/OmniSharp/omnisharp-vscode#requirements).

**Comment by SpartanJ** [comment] 2023-02-14 00:48
I won't close the issue until I'm 100% sure a freeze can happen. I've been trying to reproduce the bug but I wasn't able, but, I was able to reproduce the zombie processes, and it's fixed for sure. I tested with your same OmniSharp setup (I mean, even without MSBuild installed), and worked fine (of course OmniSharp won't work), OmniSharp with MSBuild installed works nicely as far as I could test, but I'm not a C# user so I'm not sure how good it is.
I new release with a ton of fixes will be released very soon (may be in a few hours I can build all the platforms).

**Comment by andy0x10** [comment] 2023-02-15 13:58
Thanks I will test and let you know.

**Comment by andy0x10** [comment] 2023-02-16 17:19
I haven't had the freeze since 0.4.5 so I guess it must be solved 👍

**Comment by SpartanJ** [comment] 2023-02-16 17:55
Awesome! Thank you for testing it. I'll close the issue, and if you see something wrong just let me know and I'll re-open it.

**Closed by SpartanJ** 2023-02-16 17:55 UTC
Labels: bug
