### ISSUE TITLE
FR: UI for editing default language for file extensions with multiple languages supported

### ISSUE THREAD

**Issue by iahung3** [SpartanJ/ecode#262] opened 2024-04-20 19:12 UTC
Note: I'm OK with editing configuration files, so I don't need this feature. But the issue tracking this feature disappeared, so I created a new one.

**Comment by SpartanJ** [comment] 2024-04-20 19:15
What do you mean with the title? Registering file extensions to open with ecode or something else?

**Comment by SpartanJ** [comment] 2024-04-20 19:23
If it's registering file extensions then it's a duplicate of [this one](https://github.com/SpartanJ/ecode/issues/192). And if it's for registering custom file extensions, as I said [here](https://github.com/SpartanJ/ecode/issues/261), I won't support it.

**Comment by iahung3** [comment] 2024-04-20 19:25
Someone doesn't want to edit `config.cfg` to set which language is used for a file extension, so he asked for a graphical frontend to do so right in `ecode`. But for unknown reasons, all of his issues disappeared, so I created a new one. This feature is useful for people who don't want to edit configuration files.

**Comment by iahung3** [comment] 2024-04-20 19:25
For example: someone picked SmallBASIC for .bas extension but latter decided that they want VisualBasic instead.

**Comment by SpartanJ** [comment] 2024-04-20 19:27
Oh, OK. It did not disappear, but it was a [discussion](https://github.com/SpartanJ/ecode/discussions/194), not an issue.

**Comment by iahung3** [comment] 2024-04-20 19:29
> Oh, OK. It did not disappear, but it was a [discussion](https://github.com/SpartanJ/ecode/discussions/194), not an issue.

Not my thread. Someone else submitted a FR. I have no problems with editing configuration files.

**Comment by SpartanJ** [comment] 2024-04-20 19:43
You're telling me that [iahung3](https://github.com/iahung3) and [iahung2](https://github.com/iahung2) are not the same person? OMG! [This](https://github.com/SpartanJ/ecode/issues/246) is the closest one, I remember talking about it but not having an issue for it. I don't delete issues (unless it's spam or something like that) so if someone created it must be somewhere. Anyway, a solution is needed for what you're requesting so let's keep this FR.

**Comment by iahung3** [comment] 2024-04-20 19:50
> You're telling me that [iahung3](https://github.com/iahung3) and [iahung2](https://github.com/iahung2) are not the same person? OMG! [This](https://github.com/SpartanJ/ecode/issues/246) is the closest one, I remember talking about it but not having an issue for it. I don't delete issues (unless it's spam or something like that) so if someone created it must be somewhere. Anyway, a solution is needed for what you're requesting so let's keep this FR.

Both are my account. But as I recall the original FR is posted by @superchick.

**Closed** 2024-04-21 05:23 UTC
Labels: enhancement
