### ISSUE TITLE
[0.4.5] Close tab dialog closes the tab by clicking in the body of the dialog

### ISSUE THREAD

**Issue by andy0x10** [SpartanJ/ecode#52] opened 2023-02-18 14:47 UTC
![image](https://user-images.githubusercontent.com/124288474/219872056-ce289b41-818b-4e15-9167-764b246ba750.png)

When closing a tab, you can click anywhere on the dialog (except "cancel" button) and it will behave the same as clicking "ok"

**Comment by SpartanJ** [comment] 2023-02-19 00:45
I don't know if I'm doing something "wrong" but I cannot reproduce it, I checked the implementation and I can't see how that could happen. I'll continue trying to reproduce it.

**Comment by andy0x10** [comment] 2023-02-19 13:24
That's weird, I can't reproduce it either now.. Yesterday it was 100% reproducible..  I will keep trying.

**Comment by andy0x10** [comment] 2023-02-19 14:05
Okay I can make it happen...but it seems to be semi-random...haven't found a pattern yet.

**Comment by SpartanJ** [comment] 2023-07-12 13:56
I wasn't able to reproduce it. I'll close the issue for the moment.

**Closed by SpartanJ** 2023-07-12 13:56 UTC
Labels: bug
