### ISSUE TITLE
No regex support in Ctrl+F

### ISSUE THREAD

**Issue by chatchoi** [SpartanJ/ecode#331] opened 2024-09-18 18:37 UTC
I hate Lua and I don't want to learn the sh*t named Lua patterns.

**Comment by SpartanJ** [comment] 2024-09-18 18:39
Duplicate of [https://github.com/SpartanJ/ecode/issues/147]. Mind your language or you'll be banned.

**Closed by SpartanJ** 2024-09-18 18:39 UTC
