### ISSUE TITLE
A problem while Chinese inputing

### ISSUE THREAD

**Issue by THZrry** [SpartanJ/ecode#189] opened 2024-03-10 02:32 UTC
Hello.
I don't know how to describe this. I think I may tell how could Chinese input, and then I may describe this more clearly.

We use pinyin to tell Chinese characters' pronuncations, and pinyin is formed like English.
When Chinese typing by pinyin, there will be a bar with matching words. Some input methods like Sogou will display typed pinyin too, while some like Windows pinyin not. 

I just use Windows pinyin, and when I try to input chinese, I can see the bar with matching words, but my typed pinyin disappears. It is still available but not viewable. I don't know if japanese input will behave like that, but i think it's not convinent.

![I can't see the romanji characters](https://github.com/SpartanJ/ecode/assets/140677303/4f1b6f8a-693d-4151-bf69-c626e8e9b1db)

I can't see the romanji characters, and other case:

![typing chinese in python idle](https://github.com/SpartanJ/ecode/assets/140677303/b7c388c1-cbba-4140-a64d-e4a0a9176ffc)

![in edge](https://github.com/SpartanJ/ecode/assets/140677303/96bd4cae-edda-44fb-88d4-0b110da0ed27)
These are two cases of typing Chinese. I have read an [Chinese article](https://visualgmq.gitee.io/2021/09/21/%E5%9C%A8SDL%E4%B8%AD%E5%AE%9E%E7%8E%B0%E4%B8%80%E4%B8%AA%E8%BE%93%E5%85%A5%E6%A1%86) about this, maybe it will help. Moreover, here're some Chinese words to test:
你好：n(i)h(ao)，Hello
再见：z(ai)j(ian)，Goodbye
中文：zh(ong)w(en)，Chinese(language)
编辑器：b(ian)j(i)q(i)，Editor
手机：sh(ou)j(i)，mobile phones
电脑：d(ian)n(ao)，computers
Letters in parentheses are skipable.

**Comment by SpartanJ** [comment] 2024-03-10 03:51
I think I must have broken IME support in 0.5.1, because this was explicitly developed in 0.5.0 and it was working. [Here's](https://private-user-images.githubusercontent.com/650416/280871758-e4a0384e-6bce-49bc-872e-f2d0eaa60909.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAwNDI4MDEsIm5iZiI6MTcxMDA0MjUwMSwicGF0aCI6Ii82NTA0MTYvMjgwODcxNzU4LWU0YTAzODRlLTZiY2UtNDliYy04NzJlLWYyZDBlYWE2MDkwOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxMFQwMzQ4MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMDYxYzBhMTc4N2U0MGM2ZTMwOGM2NWU1YWRhMmIzMTcwNzYxMTU3N2YxM2RjNzdhNTRhOTIzMWM2MmZhNmRhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.4sZo_cZseq6SYy2Wmt-r_eot_5kGBoVh8JzloW28QNU) the screenshot I posted for the release.

**Comment by SpartanJ** [comment] 2024-03-10 04:07
Yes, I broke it while fixing [another issue](https://github.com/SpartanJ/ecode/issues/115).

**Comment by THZrry** [comment] 2024-03-10 04:15
I have tried the old version,  it's right...
Maybe this issue can be closed.

**Comment by SpartanJ** [comment] 2024-03-10 04:35
Nono, I need to fix it for the next version haha. The fix is trivial on macOS and Linux but Windows SDL2 implementation of IME has some bug that is problematic. I'll have to make some tests on Windows.

**Comment by SpartanJ** [comment] 2024-03-10 15:12
Regression fixed, it will be part of the next minor release.

**Comment by iahung2** [comment] 2024-03-10 17:40
Maybe related: https://github.com/SpartanJ/ecode/discussions/163

**Comment by iahung2** [comment] 2024-03-11 13:26
> Regression fixed, it will be part of the next minor release.

I build from source using the latest code. It doesn't fix my problem.

@THZrry Does it work for you?

**Comment by SpartanJ** [comment] 2024-03-11 13:29
Please clarify your problem. Based on what you said you're talking about a different problem.

**Comment by iahung2** [comment] 2024-03-12 05:10
> Please clarify your problem. Based on what you said you're talking about a different problem.

I don't know. My language is not Chinese. It's based on Latin script with a ton of tone marks.

**Comment by iahung2** [comment] 2024-03-12 05:16
Tested on Pragtical. Same problem. OK. A code editor is for code but not for normal text. In code, I use English comments anyway.

**Comment by SpartanJ** [comment] 2024-03-12 14:53
> Why don't you think a bit differently?

Mmh maybe because you're not giving me enough information. I still don't even know what's the language you're trying to input and how you're trying to input it, you use IME to insert the characters? Does sometimes render a glyph (even if it's wrong) or you never can insert it? Which OS you're trying to use? Can you send me a video or some screenshots?

**Comment by THZrry** [comment] 2024-03-12 14:56
I have checked the font files.

Ecode shows Chinese ( and other non-ASCII chars? ) by fallback font. LiteXL also supports Chinese but not offical. See this lite-xl/lite-xl#944 You can make lite-xl show Chinese by specificing fallback font or changing default font instead. 

So if the fallback font is even helpless for some characters, will Ecode use system fonts?

**Comment by SpartanJ** [comment] 2024-03-12 14:59
> So if the fallback font is even helpless for some characters, will Ecode use system fonts?

Not for the moment, I need to investigate how to locate them on each OS. That's pending.

**Comment by THZrry** [comment] 2024-03-12 15:06
That's definitely a hard work. Maybe this can be left for now, because there's one existing way to change a font file.

**Comment by iahung3** [comment] 2024-03-13 16:31
> > So if the fallback font is even helpless for some characters, will Ecode use system fonts?
> 
> Not for the moment, I need to investigate how to locate them on each OS. That's pending.

What do you think about using `fontconfig` and `freetype2`? This will also solve the problem with sub-pixel hinting.

**Comment by iahung2** [comment] 2024-03-13 16:38
> > So if the fallback font is even helpless for some characters, will Ecode use system fonts?
> 
> Not for the moment, I need to investigate how to locate them on each OS. That's pending.

What do you think about using `fontconfig` and `freetype2`? This will also solve the problem with sub-pixel hinting.

**Comment by SpartanJ** [comment] 2024-03-13 16:49
> What do you think about using fontconfig and freetype2? This will also solve the problem with sub-pixel hinting.

Regarding `fontconfig`, it's a possible alternative. I always first try to solve it internally, otherwise I'll try to use an easy to build and small open-source library. So I need to analyze if fits our needs.

Regarding freetype2. ecode *does* use freetype2 for all its font rendering. sub-pixel hinting is not solved by freetype2. freetype2 will provide you the glyphs but the hinting must be done by the software, since sub-pixel hinting depends on the background color, that's the main complexity. On the ecode case sub-pixel hinting would require to render everything into a frame-buffer and implement the hinting with a pixel-shader, the required changes are not trivial and it's also computationally expensive.

BTW I still have very little information about your issue. If you can provide more information that would be really helpful. Thanks

**Comment by SpartanJ** [comment] 2024-03-13 17:08
With freetype you'll basically hint the glyph renderer to render with LCD filters into a pixel-buffer, but all the real logic and rendering goes after that, if you're really interested read [this](http://arkanis.de/weblog/2023-08-14-simple-good-quality-subpixel-text-rendering-in-opengl-with-stb-truetype-and-dual-source-blending) article which goes very much in depth about the whole process.

**Closed** 2024-05-01 21:24 UTC
Labels: bug, ready for release
