### ISSUE TITLE
[0.4.3] A file added/removed from a subfolder is not detected

### ISSUE THREAD

**Issue by andy0x10** [SpartanJ/ecode#28] opened 2023-02-02 17:27 UTC
If I add/remove a file from an external tool (eg Windows Explorer) to the active project folder, then ecode will detect that file...but if this is done in a sub-folder it is not detected.  

This is quite annoying as sometimes I add/remove files from Unity and the aren't detected.  It would be great to have this feature.

Perhaps some way to refresh the folder view at least?  Currently I have to toggle "Show Hidden Files" for it to update.  Perhaps a Refresh button in the context-menu or F5 shortcut?  Ideally I guess it would monitor for file changes in all folders.

Thanks,

**Comment by SpartanJ** [comment] 2023-02-02 17:30
Oh, this is a duplicate of #20. I never found a way to reproduce it, but I think you gave me the details I need. Yes, I'll add a refresh button too, but I'll try to solve the original issue haha.

**Closed** 2023-02-03 02:50 UTC
Labels: bug
