### ISSUE TITLE
No write permissions anywhere Win10

### ISSUE THREAD

**Issue by emeraldtip** [SpartanJ/ecode#103] opened 2023-09-06 05:56 UTC
Every time I try to save a file somewhere ecode says that I have no write permissions.
Also if there's no write permissions in the folder the file is located in, the linter???? causes ecode to crash.

**Comment by SpartanJ** [comment] 2023-09-06 14:21
This must be what we already discussed [here](https://github.com/SpartanJ/ecode/issues/85). 

> Also if there's no write permissions in the folder the file is located in, the linter???? causes ecode to crash.

Can you give me more context? Language used, linter, your logs?

**Comment by emeraldtip** [comment] 2023-09-07 07:17
![image](https://github.com/SpartanJ/ecode/assets/48155462/7e780ced-14bf-4b20-9064-c9be641d9a14)
and
![image](https://github.com/SpartanJ/ecode/assets/48155462/2bd820a0-d2ff-4323-8f39-4321e3cb3b53)

But now suddenly I can't reproduce the crashing with no write permissions when autocomplete kicks in?
I'll look into it more later.


Every time I try to save a file even if I've created the file outside of the onedrive folder, with ecode, 2 seconds before saving the file, ecode tells me that It couldn't write into the file:

https://github.com/SpartanJ/ecode/assets/48155462/c406fdc6-e0e4-459f-af1e-34e6d22b8e82

(I know that it's running from a onedrive folder, but this also happens when I run the application instance that's in downloads)
```
2023-09-07 10:06:27 - INFO: eepp initialized
2023-09-07 10:06:27 - INFO: ecode starting with these command line arguments: C:\Users\karlj\Downloads\vaibad.cpp
2023-09-07 10:06:27 - INFO: C:\Users\karlj\AppData\Roaming\ecode\config.cfg loaded in 0.31ms
2023-09-07 10:06:27 - INFO: C:\Users\karlj\AppData\Roaming\ecode\state.cfg loaded in 0.12ms
2023-09-07 10:06:28 - INFO: Engine Initialized Succesfully.
	Version: eepp version 2.6.1 (codename: "Anathapindika")
	Build time: Jul 11 2023 17:50:18
	Platform: Windows
	OS: Microsoft Windows 10
	Arch: x64
	CPU Cores: 16
	Process Path: C:\Users\karlj\OneDrive\ecode\
	Current Working Directory: C:\Users\karlj\Downloads
	Disk Free Space: 19.77 GiB
	Window/Input Backend: SDL 2.26.2
	GL Backend: OpenGL 2
	GL Vendor: NVIDIA Corporation
	GL Renderer: NVIDIA GeForce RTX 2060/PCIe/SSE2
	GL Version: 4.6.0 NVIDIA 512.96
	GL Shading Language Version: 4.60 NVIDIA
	Resolution: 3840x2115
2023-09-07 10:06:28 - INFO: ecode version 0.4.9 (codename: "Vajra") initializing
2023-09-07 10:06:28 - INFO: Window creation took: 275.72 ms
2023-09-07 10:06:28 - INFO: C:\Users\karlj\AppData\Roaming\ecode\keybindings.cfg loaded in 1.00ms
2023-09-07 10:06:28 - INFO: StyleSheet loaded in: 5.932 ms.
2023-09-07 10:06:28 - INFO: StyleSheet loaded in: 0.027 ms.
2023-09-07 10:06:28 - INFO: Syntax definitions loaded in 6.24 ms.
2023-09-07 10:06:28 - INFO: StyleSheet loaded in: 1.463 ms.
2023-09-07 10:06:28 - INFO: Texture ID 1 loaded in 45.336 ms.
2023-09-07 10:06:28 - INFO: Texture ID 2 loaded in 0.256 ms.
2023-09-07 10:06:28 - INFO: Texture ID 3 loaded in 1.214 ms.
2023-09-07 10:06:28 - INFO: Texture ID 4 loaded in 0.801 ms.
2023-09-07 10:06:28 - INFO: Texture ID 5 loaded in 1.062 ms.
2023-09-07 10:06:28 - INFO: Texture ID 6 loaded in 0.872 ms.
2023-09-07 10:06:28 - INFO: Texture ID 7 loaded in 0.466 ms.
2023-09-07 10:06:28 - INFO: Texture ID 8 loaded in 7.971 ms.
2023-09-07 10:06:28 - INFO: Texture ID 9 loaded in 1.202 ms.
2023-09-07 10:06:28 - INFO: Color Schemes loaded in 1.44ms.
2023-09-07 10:06:28 - INFO: SyntaxDefinitionManager loaded custom languages in: 0.19 ms
2023-09-07 10:06:28 - INFO: Terminal Color Schemes loaded in 0.98ms.
2023-09-07 10:06:28 - INFO: Base UI took: 421.82 ms
2023-09-07 10:06:28 - INFO: Texture ID 10 loaded in 1.921 ms.
2023-09-07 10:06:28 - INFO: Texture ID 11 loaded in 1.381 ms.
2023-09-07 10:06:28 - INFO: Texture ID 12 loaded in 0.112 ms.
2023-09-07 10:06:28 - INFO: Settings Menu took: 72.91 ms
2023-09-07 10:06:28 - INFO: Texture ID 13 loaded in 1.413 ms.
2023-09-07 10:06:28 - INFO: Texture ID 14 loaded in 0.436 ms.
2023-09-07 10:06:28 - INFO: Complete UI took: 505.64 ms
2023-09-07 10:06:28 - INFO: Document "C:\Users\karlj\Downloads\vaibad.cpp" loaded in 0.44ms.
2023-09-07 10:06:28 - INFO: Init ProjectTreeView took: 766.41 ms
2023-09-07 10:06:28 - INFO: First update took: 819.80 ms
2023-09-07 10:06:28 - INFO: First frame took: 840.65 ms
2023-09-07 10:06:28 - INFO: LSPClientServer server clangd calling initialize
2023-09-07 10:06:28 - INFO: LSPClientServer server clangd calling initialized
2023-09-07 10:06:28 - INFO: LSPClientServer server clangd calling textDocument/didOpen
2023-09-07 10:06:28 - INFO: LSPClientServer server clangd calling textDocument/documentSymbol
2023-09-07 10:06:28 - INFO: LSPClientServer server clangd calling 
2023-09-07 10:06:29 - INFO: LinterPlugin::runLinter for C:\Users\karlj\Downloads\vaibad.cpp took 84.04ms. Found: 0 matches. Errors: 0, Warnings: 0, Notices: 0.
2023-09-07 10:06:30 - INFO: Texture ID 15 loaded in 0.561 ms.
2023-09-07 10:06:30 - INFO: LSPClientServer server clangd calling textDocument/hover
2023-09-07 10:06:39 - INFO: Document "C:\Users\karlj\Downloads\test.py" loaded in 1.64ms.
2023-09-07 10:06:39 - INFO: LSPClientServer server pylsp calling initialize
2023-09-07 10:06:39 - INFO: LinterPlugin::runLinter for C:\Users\karlj\Downloads\test.py took 111.13ms. Found: 0 matches. Errors: 0, Warnings: 0, Notices: 0.
2023-09-07 10:06:41 - INFO: LSPClientServer server pylsp calling initialized
2023-09-07 10:06:41 - INFO: LSPClientServer server pylsp calling textDocument/didOpen
2023-09-07 10:06:41 - INFO: LSPClientServer server pylsp calling textDocument/didChange
2023-09-07 10:06:41 - INFO: LSPClientServer server pylsp calling textDocument/didChange
2023-09-07 10:06:41 - INFO: LSPClientServer server pylsp calling textDocument/didChange
2023-09-07 10:06:41 - INFO: LSPClientServer server pylsp calling textDocument/didChange
2023-09-07 10:06:41 - INFO: LSPClientServer server pylsp calling textDocument/didChange
2023-09-07 10:06:41 - INFO: LSPClientServer server pylsp calling textDocument/didChange
2023-09-07 10:06:41 - INFO: LSPClientServer server pylsp calling textDocument/didChange
2023-09-07 10:06:41 - INFO: LSPClientServer server pylsp calling textDocument/hover
2023-09-07 10:06:41 - INFO: LSPClientServer server pylsp calling textDocument/documentSymbol
2023-09-07 10:06:41 - INFO: LSPClientServer server pylsp calling textDocument/didChange
2023-09-07 10:06:41 - INFO: LSPClientServer server pylsp calling textDocument/didChange
2023-09-07 10:06:41 - INFO: LSPClientServer server pylsp calling textDocument/didChange
2023-09-07 10:06:41 - INFO: LSPClientServer server pylsp calling textDocument/signatureHelp
2023-09-07 10:06:42 - INFO: LinterPlugin::runLinter for C:\Users\karlj\Downloads\.RG6T8VSp.test.py took 103.85ms. Found: 0 matches. Errors: 0, Warnings: 0, Notices: 0.
2023-09-07 10:06:42 - INFO: LSPClientServer server pylsp calling textDocument/documentSymbol
2023-09-07 10:06:47 - INFO: LSPClientServer server pylsp calling textDocument/didChange
2023-09-07 10:06:47 - INFO: LSPClientServer server pylsp calling textDocument/didChange
2023-09-07 10:06:47 - INFO: LinterPlugin::runLinter for C:\Users\karlj\Downloads\.KtzupV0R.test.py took 95.36ms. Found: 0 matches. Errors: 0, Warnings: 0, Notices: 0.
2023-09-07 10:06:48 - INFO: LSPClientServer server pylsp calling textDocument/didChange
2023-09-07 10:06:48 - INFO: LSPClientServer server pylsp calling textDocument/didChange
2023-09-07 10:06:48 - INFO: LSPClientServer server pylsp calling textDocument/didChange
2023-09-07 10:06:48 - INFO: LSPClientServer server pylsp calling textDocument/didChange
2023-09-07 10:06:48 - INFO: LSPClientServer server pylsp calling textDocument/didChange
2023-09-07 10:06:48 - INFO: LSPClientServer server pylsp calling textDocument/didChange
2023-09-07 10:06:48 - INFO: LSPClientServer server pylsp calling textDocument/didChange
2023-09-07 10:06:49 - INFO: LSPClientServer server pylsp calling textDocument/didChange
2023-09-07 10:06:49 - INFO: LSPClientServer server pylsp calling textDocument/didChange
2023-09-07 10:06:49 - INFO: LSPClientServer server pylsp calling textDocument/didChange
2023-09-07 10:06:49 - INFO: LSPClientServer server pylsp calling textDocument/didChange
2023-09-07 10:06:49 - INFO: LSPClientServer server pylsp calling textDocument/didChange
2023-09-07 10:06:49 - INFO: LSPClientServer server pylsp calling textDocument/didChange
2023-09-07 10:06:49 - INFO: LSPClientServer server pylsp calling textDocument/didChange
2023-09-07 10:06:50 - INFO: LSPClientServer server pylsp calling textDocument/didChange
2023-09-07 10:06:50 - INFO: LSPClientServer server pylsp calling textDocument/didChange
2023-09-07 10:06:50 - INFO: LinterPlugin::runLinter for C:\Users\karlj\Downloads\.hZvASHgO.test.py took 110.72ms. Found: 2 matches. Errors: 2, Warnings: 0, Notices: 0.
2023-09-07 10:06:51 - INFO: LSPClientServer server pylsp calling textDocument/documentSymbol
2023-09-07 10:06:53 - INFO: LSPClientServer server pylsp calling textDocument/hover
2023-09-07 10:06:53 - INFO: LSPClientServer server pylsp calling textDocument/didClose
2023-09-07 10:06:54 - INFO: LSPClientServer server clangd calling textDocument/didClose
2023-09-07 10:06:55 - INFO: LSPClientServer:shutdown: clangd
2023-09-07 10:06:55 - INFO: LSPClientServer server clangd calling shutdown
2023-09-07 10:06:55 - INFO: LSPClientServer server clangd calling exit
2023-09-07 10:06:55 - INFO: LSPClientServer:shutdown: pylsp
2023-09-07 10:06:55 - INFO: LSPClientServer server pylsp calling shutdown
2023-09-07 10:06:55 - INFO: LSPClientServer server pylsp calling exit
2023-09-07 10:06:55 - INFO: eepp stoped
```

**Comment by SpartanJ** [comment] 2023-09-09 03:51
Thanks, I'm able to reproduce it. I'll fix it ASAP.

**Comment by SpartanJ** [comment] 2023-09-09 16:09
BTW this is happening because [windows is ridiculous](https://stackoverflow.com/a/75931329).
If you can't wait for a solution you can simply remove the read-only flag to the Downloads folder. ecode verifies that flag to know if it's possible to write the file, and respects it, but it's incorrect, it actually can write into it (it will even create the file).

**Comment by SpartanJ** [comment] 2023-09-09 20:19
A [fix has been pushed](https://github.com/SpartanJ/eepp/commit/e479760ec8348c9f1733438c2f7b976922679885), it will be available in the next release, meanwhile you can use this build [ecode-windows-0.4.9-x86_64.zip](https://github.com/SpartanJ/ecode/files/12566612/ecode-windows-0.4.9-x86_64.zip) that contains the fixes.

**Comment by emeraldtip** [comment] 2023-09-11 05:05
Tysm!
Yeah Windows is pretty shit, especially that permissions thing (but the software I use isn't supported on Linux)

**Closed** 2023-11-06 23:24 UTC
Labels: bug, released
