### ISSUE TITLE
Selected text are deleted while alt+tabbing windows on linux

### ISSUE THREAD

**Issue by orjanv** [SpartanJ/ecode#221] opened 2024-03-29 10:13 UTC
If I select text in the editor, then alt+tab to another window, and back again, the selected text has disappeared.

**Comment by SpartanJ** [comment] 2024-03-29 15:22
Thanks for reporting it, that's weird, this was fixed in 0.5.1 (issue #115), can you provide your desktop environment and if you're using X11 or Wayland? Thanks

**Comment by orjanv** [comment] 2024-03-29 16:56
Debian GNU/Linux 12 (bookworm) x86_64
DE: LXQt 1.2.0
WM: Xfwm4
X11

**Comment by SpartanJ** [comment] 2024-04-06 23:55
Hi @orjanv !
I'm trying to reproduce the bug with no success. I installed Debian 12 with LXQt+Xfwm4+X11, but I cannot reproduce the bug, here's a video:

https://github.com/SpartanJ/ecode/assets/650416/3237a2be-61c1-4d81-85a0-da53843b8d84



Do you see anything different from your environment? I'm missing something?
Thanks

**Comment by SpartanJ** [comment] 2024-07-16 19:29
Closing due to the impossibility of reproduction and lack of user-feedback.

**Closed by SpartanJ** 2024-07-16 19:29 UTC
Labels: bug, question, linux
