### ISSUE TITLE
Ecode deleting contents of files on windows

### ISSUE THREAD

**Issue by emeraldtip** [SpartanJ/ecode#114] opened 2023-12-26 14:47 UTC
So I was editing some qlc showfiles for some lighting things in ecode (cause QLC has a horrible preshow configuring mode) and I tried to open the same file in 2 ecode windows at once and it just wiped the contents of the file completely. Luckily I still had qlc opened so I could overwrite the deletion. When I closed all ecode windows after that and reopened the file in ecode it deleted the contents again.

Video:

https://github.com/SpartanJ/ecode/assets/48155462/b22acadb-0a81-456f-b113-6918748eb1b2

If I just open the folder in ecode and then navigate to the file from inside ecode, everything works just fine.
Is this an issue with storing the last state of ecode?

**Comment by SpartanJ** [comment] 2023-12-26 15:08
I think it's not being able to load the file because it's locked or some crappy Window thingy, the file is not empty. I'll try to reproduce it, thanks!

**Comment by SpartanJ** [comment] 2024-01-02 22:29
Ok, the bug does not have to do with the file being open or nothing like that, the bug is that the file path is not properly parsed and believes that the file does not exists, in consequence creates a new empty file with that name. So I was wrong, the file is empty. Basically it will happen with any file opened from the file explorer with ecode that contains non ASCII characters. This is an important bug, I think may release a small bugfix version soon.
I already pushed a fix [here](https://github.com/SpartanJ/eepp/commit/5d592c21c605ab8ab24158435a1342ba93136145).

**Closed** 2024-02-20 23:13 UTC
Labels: bug, windows, ready for release
